### ISSUE TITLE
Deploy failing on AWS security token

### ISSUE THREAD

**Issue by billgeo** [linz/qgis-plugin-repository#146]
See here https://github.com/linz/qgis-plugin-repository/runs/2936849660?check_suite_focus=true
```
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ***
    aws-secret-access-key: ***
    aws-region: ap-southeast-2
    role-to-assume: ***
  
  
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
Error: The security token included in the request is invalid.

```

**Comment by SPlanzer** [comment]
As a starting point we need to confirm is the li-small-apps service account keys have been rotated

**Comment by SPlanzer** [comment]
LISmallAppsServiceAccount was disabled due to inactivity. These are only used for deployment so this is understandable. 

How do we manage keys so that they do not get considered inactive?  
Is it bad practice for CI to use then at a set frequency to keep them of a active status?

**Comment by SPlanzer** [comment]
FYI @billgeo Account is now of active status - Closing

**Comment by billgeo** [comment]
Thanks @SPlanzer. Not sure about best practice there, but I assume almost all our other repos with AWS secrets would have a similar issue? Could always do a scheduled CI, not sure that there would be any harm there, and would at least test if the secrets are still active.
