### ISSUE TITLE
Continuous Delivery

### ISSUE THREAD

**Issue by SPlanzer** [linz/qgis-plugin-repository#28]
This is a step that may be executed after automated deployment of the test environment and end to end tests pass.  

The step is to require manual intervention where by it should not be executed until a developer has reviewed the results of all the PR, tests, linting, formatting, test deployment and end to end tests. The developer should then be able to run a deployment script to deploy to production. 

This must ensure that the deployed version self reports its version (see #24) and that correct git source code control (such as tagging and release) is in place. 

Deployment should not affect DNS mapping

**Comment by billgeo** [comment]
Done
